idf_component_register(
    SRCS "main.c"
         "demo_navigation.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
         "demo_radio.c"
         "demo_wifi.c"
         "demo_ble.c"
         "demo_low_power.c"
         "demo_balance.c"
         "serial_screenshot.c"
         "demo_balance_direct.c"
         "net_link.c"
         "wifi_store.c"
         "wifi_pick.c"
         "http_json.c"
         "glm_quota.c"
         "demo_settings.c"
         "../assets/fonts/ui_font_cjk_12.c"
         "../assets/fonts/ui_font_cjk_24.c"
    INCLUDE_DIRS "." "../managed_components/lvgl__lvgl/src/draw/snapshot" "../managed_components/lvgl__lvgl/src/misc"
    REQUIRES bsp bt esp_event esp_hw_support esp_netif esp_timer esp_wifi nvs_flash esp_http_client json mbedtls
)
